<?php 
    $data = $this->getData();
    //$orderList = $data["orderList"];
    $srb_public_url = trim($data['srb_public_url']);
    $token = $data['token'];
    $api_production = $data['api_production'];
    $weight_unit = $data['weight_unit'];

    $weighUnit = array(
        'kilogram' => '',
        'gram' => '',
        'pound' =>'',
        'ounce' =>''
    );
    $weighUnit[$weight_unit] = 'selected';
?>
<div class="srb-wrapper">
    <!-- Start srb-menu -->
    <?php echo $this->getChildHtml('menu'); ?> 
    <!-- Start srb-content -->
    <div class="srb-content">
        <div class="srb-content-head">
            <span class="srb-title"><?php echo $this->__("Configuration"); ?></span>
        </div>
        <hr/>
        <div  style="width: 800px; margin: 0 auto; margin-top: 50px;">
                <table style="width: 100%;">
                    <tr id="srb-success-msg" style="display: none;">
                        <td colspan="2">
                            <ul class="messages">
                                <li class="success-msg" id="srb-success-text"></li>
                            </ul>
                        </td>
                    </tr>
                    <tr> 
                        <td colspan="2"> 
                            <div class="notification-global notification-global-warning" style="margin-bottom: 3px; border: 1px solid orange;">
                                <strong style="color:red"><?php echo $this->__("Important"); ?>: </strong>
                                <span>
                                    <?php echo $this->__("If you change the API token, the previous synchronized data will be lost."); ?>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <tr> 
                        <td> 
                            <h3> <span style="color: red;"> *</span><?php echo $this->__("API Token"); ?></h3> 
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td> 
                            <input id="input_token" class="input-text" type="text" name='input_token' style="width: 100%;" value="<?php echo $token; ?>" />
                        </td>
                        <td> 
                            <button name='btn_save' value="ok" onclick="updateToken()">
                                <?php echo $this->__("Save"); ?>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="validation-advice" id="wrong-api" style="display: none;"></div>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-top: 50px;"> </td>
                        <td> </td>
                    </tr>
                    <tr>
                        <td> 
                            <h3><?php echo $this->__("Production environment"); ?></h3>
                            <label > 
                                <input type="radio" name="answer" id="radio1" value="1"
                                <?php echo ($api_production=='1')?'checked':'onclick="changeProductionStatus(1, this)"' ?> > 
                                <?php echo $this->__("Yes"); ?>
                            </label> <br/> 

                            <label>
                                <input type="radio" name="answer" id="radio0" value="0"
                                <?php echo ($api_production=='0')?'checked':'onclick="changeProductionStatus(0, this)"' ?> > 
                                <?php echo $this->__("No"); ?>
                            </label>
                        </td>
                    </tr>
                    <tr>
                        <td> 
                            <a href="<?php echo $srb_public_url; ?>" target="_blank">
                                <?php echo $this->__("No account? Create one here"); ?>
                            </a>
                        </td>
                        <td> </td>
                    </tr>
                    <tr>
                        <td style="padding-top: 50px;"> 
                            <h3><?php echo $this->__("Unit of weight"); ?></h3>
                            <label> 
                                <select id="weight-unit" style="width: 165px;">
                                    <option <?php echo $weighUnit['kilogram']; ?> value="kilogram">Kilogram</option>
                                    <option <?php echo $weighUnit['gram']; ?> value="gram">Gram</option>
                                    <option <?php echo $weighUnit['pound']; ?> value="pound">Pound</option>
                                    <option <?php echo $weighUnit['ounce']; ?> value="ounce">Ounce</option>
                                </select>
                            </label>

                            <label style="display: inline-block;"> 
                                <button name='btn_save' value="ok" onclick="updateWeightUnit()">
                                    <?php echo $this->__("Save"); ?>
                                </button>
                            </label>
                        </td>
                    </tr>
                </table>
        </div>
    </div>
    <!-- end srb-content -->
</div>    
<script>
    function changeProductionStatus(status, me)
    {
        var message = '<?php echo $this->__("If you change working environment (sandbox, production), the previous synchronized data will be lost."); ?>';
        var conf = confirm(message);
        if (conf == true) {
            new Ajax.Request('', {
                method: 'post',
                parameters: {api_status: status},
                onSuccess: function(response){
                    location.reload();
                },
                onFailure:  function(response){}
            });
        } else {
            radio = {
                "0" : document.getElementById('radio1'),
                "1" : document.getElementById('radio0')
            }
            me.checked = false;
            radio[status].checked = true;
        }
    }

    function updateToken()
    {
        var message = '<?php echo $this->__("If you change the API token, the previous synchronized data will be lost."); ?>';
        var sms_incurrect = '<?php echo $this->__("Your API token is incorrect"); ?>';
        var sms_require = '<?php echo $this->__("This is a required field"); ?>';
        var sms_success = '<?php echo $this->__("API key has been saved."); ?>';
        var token = document.getElementById("input_token").value;
        var wrong_api = document.getElementById('wrong-api');
        var success_msg = document.getElementById('srb-success-msg');
        var sucess_text = document.getElementById('srb-success-text');
        if (token.trim() != '') {
            var conf = confirm(message);
            if (conf == true) {
                new Ajax.Request('', {
                   method: 'post',
                   parameters: {input_token: token},
                   onSuccess: function(response){
                        if(response.responseText == "incorrect"){
                            wrong_api.style.display = "block";
                            wrong_api.innerHTML = sms_incurrect;
                        } else {
                            success_msg.style.display = "table-row";
                            sucess_text.innerHTML = sms_success;
                            setTimeout(function() {
                                success_msg.style.display = "none";
                            }, 5000);
                            
                        }
                   },
                   onFailure:  function(response){}
                });
            }
        }else{
            wrong_api.style.display = "block";
            wrong_api.innerHTML = sms_require;
        }
    }

    function updateWeightUnit()
    {
        var weight_unit = document.getElementById("weight-unit").value;
        new Ajax.Request('', {
           method: 'post',
           parameters: {weight_unit: weight_unit},
           onSuccess: function(response){
                location.reload();
           },
           onFailure:  function(response){}
        });
    }
</script>
