<?php 
    $data = $this->getData();
    $limit_item = $data['limit_item'];
    $productList = $data["productList"];
    $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
    $public_url = $data['srb_product_url'];
    $form_key = Mage::getSingleton('core/session')->getFormKey();
?>
<div class="srb-wrapper">
    <?php echo $this->getChildHtml('menu'); ?> 
    <!-- Start srb-content -->
    <div class="srb-content">
        <div class="srb-content-head">
            <span class="srb-title"><?php echo $this->__("My products"); ?></span>
            <span class="srb-btn" onclick="syncAll()"><?php echo $this->__("Synchronize all"); ?></span>
            <span class="srb-btn" onclick="syncNew()"><?php echo $this->__("Synchronize New only"); ?></span>
            <span class="srb-btn srb-find">
                <a href="<?php echo trim($public_url).'/products'; ?>" target="_blank">
                    <?php echo $this->__("Check on ShopRunBack"); ?>
                </a>
            </span>
        </div>
        <p class="srb-spam"><?php echo $this->__("Description of product"); ?></p>
        <div class="srb-table-blog">
            <table class="srb-table" style="width: 100%;">
                <thead>
                    <tr>
                        <th><?php echo $this->__("No"); ?></th>
                        <th><?php echo $this->__("Product"); ?></th>
                        <th><?php echo $this->__("Reference"); ?></th>
                        <th><?php echo $this->__("Last synchronization"); ?></th>
                        <th><?php echo $this->__("Synchronize"); ?></th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $i=0;
                        if (isset($_GET['page'])) {
                            $i = (($_GET['page']-1)* $limit_item);
                        }
                        foreach ($productList as $product) {
                            $i++;
                            $no = $i;
                            $id = $product['id'];
                            $label = $product['name'];
                            $product_map = $product['data'];
                            $last_sent_at = $product_map['last_sent_at'];
                            $srb_product_url = $public_url.'products/'.$product_map['id_item_srb'];
                            $target = "_blank";
                            $popup_url  ="-";
                            $cms_id = $product_map['id_item'];
                            $update_form = "<button class='srd-syn' onclick='syncItem($id)'>".$this->__("Synchronize")."</button>";
                            if (trim($last_sent_at) == "") {
                                $last_sent_at  = "-";
                                $cms_id = "-";
                                $srb_product_url = "#";
                                $target = "";
                            } else {
                                $popup_url = "
                                    <a href='$srb_product_url' class='srb-link' target='$target'> 
                                    ↗ </a>";
                            }
                            echo "
                                <tr id='$id'>
                                    <td>$no</td>
                                    <td>$label </td>
                                    <td class='cms_id'>$cms_id </td>
                                    <td class='sent_time'>$last_sent_at</td>
                                    <td>
                                        $update_form
                                    </td>
                                    <td class='url_item'>$popup_url</td>
                                </tr>
                            ";
                        }
                    ?>
                </tbody>
            </table>
            <?php echo $this->getChildHtml('pagination'); ?> 
            <?php
                // $numItem = Mage::getResourceModel('catalog/product_collection')->getSize();
                // $product_dao = Mage::helper('srb_shipback/product');
                // $product_dao->setPagination($numItem);
            ?>
        </div>
    </div>
    <!-- end srb-content -->
</div>    
<script>
    function syncAll()
    {
        new Ajax.Request('', {
           method: 'post',
           parameters: {sync_type: 'sync_all'},
           onSuccess: function(response){
                   location.reload();
           },
           onFailure:  function(response){}
        });
    }

    function syncNew()
    {
        new Ajax.Request('', {
           method: 'post',
           parameters: {sync_type: 'sync_new'},
           onSuccess: function(response){
                   location.reload();
           },
           onFailure:  function(response){}
        });
    }

    function syncItem(id)
    {   
        var srb_url = "<?php echo $public_url; ?>" + "products/";
        var tr = document.getElementById(id);
        var cms_id = tr.getElementsByClassName('cms_id')[0];
        var sent_time = tr.getElementsByClassName('sent_time')[0];
        var url_item = tr.getElementsByClassName('url_item')[0];
        new Ajax.Request('', {
           method: 'post',
           parameters: {id_item: id},
           onSuccess: function(response){
                var obj = JSON.parse(response.responseText);
                if (obj.code == 200 || obj.code == 201) {
                    srb_url += obj.id;
                    cms_id.innerHTML = id;
                    sent_time.innerHTML = obj.updated_at;
                    url_item.innerHTML = "<a href='"+srb_url+"' class='srb-link' target='_blank'> ↗ </a>";
                }
            },
           onFailure:  function(response){}
        });
    }

    function findOnSRB()
    {
        window.location ="<?php echo trim($public_url).'/products'; ?>";
    }// end function
</script>
